import { useState, useEffect } from 'react';
import { useTheme } from '../lib/ThemeContext';

export default function ApprovalPanel({ email, route, onApprove, onReject }) {
  const [isEditing, setIsEditing] = useState(false);
  const [editedResponse, setEditedResponse] = useState('');
  const [feedback, setFeedback] = useState('');
  const { isDark } = useTheme();

  // Update editedResponse when email changes
  useEffect(() => {
    setEditedResponse(email.generated_response || '');
    setIsEditing(false);
    setFeedback('');
  }, [email]);

  const handleApprove = () => {
    onApprove(editedResponse);
  };
  const handleReject = () => {
    onReject();
  };

  return (
    <div className={`rounded-2xl p-6 ring-1 backdrop-blur-xl animate-fade-in transition-colors duration-300 ${
      isDark 
        ? 'bg-gradient-to-br from-white/10 to-white/[0.02] ring-white/10' 
        : 'bg-white ring-slate-200 shadow-lg'
    }`}>
      {/* Route-specific UI */}
      {route === 'AI_AGENT' && (
        <div className="mb-6 p-4 bg-emerald-500/10 ring-1 ring-emerald-500/20 rounded-xl">
          <p className="text-sm font-bold text-emerald-400 mb-1.5 flex items-center gap-2">
            <span aria-hidden="true">🤖</span>
            AI Agent Response Ready
          </p>
          <p className={`text-xs leading-relaxed ${isDark ? 'text-emerald-300/80' : 'text-emerald-700'}`}>
            This response was generated by the AI agent using your FAQ knowledge base. 
            Review and edit if needed, then approve to send.
          </p>
        </div>
      )}

      {route === 'HUMAN_REQUIRED' && (
        <div className="mb-6 p-4 bg-amber-500/10 ring-1 ring-amber-500/20 rounded-xl">
          <p className="text-sm font-bold text-amber-400 mb-1.5 flex items-center gap-2">
            <span aria-hidden="true">👤</span>
            Manual Response Required
          </p>
          <p className={`text-xs leading-relaxed ${isDark ? 'text-amber-300/80' : 'text-amber-700'}`}>
            This email requires human judgment. Please compose a response below.
          </p>
        </div>
      )}

      {/* Suggested Response */}
      <div className="mb-6">
        <label className={`block text-xs font-semibold mb-3 uppercase tracking-wider flex items-center gap-2 ${
          isDark ? 'text-slate-500' : 'text-slate-500'
        }`}>
          {route === 'AI_AGENT' ? (
            <>
              <span aria-hidden="true">🤖</span>
              AI-Generated Response
            </>
          ) : (
            <>
              <span aria-hidden="true">✍️</span>
              Your Response
            </>
          )}
        </label>
        {isEditing || !editedResponse ? (
          <textarea
            value={editedResponse}
            onChange={(e) => setEditedResponse(e.target.value)}
            className={`w-full min-h-[320px] p-4 text-sm rounded-xl ring-1 transition-all focus:ring-2 focus:ring-[#7BAFD4] focus:outline-none resize-y leading-relaxed ${
              isDark 
                ? 'bg-[#050B16]/60 text-slate-200 ring-white/10 placeholder:text-slate-500' 
                : 'bg-slate-50 text-slate-900 ring-slate-200 placeholder:text-slate-400'
            }`}
            placeholder="Type your response here..."
          />
        ) : (
          <div className={`w-full min-h-[320px] max-h-[400px] p-4 overflow-y-auto text-sm whitespace-pre-wrap ring-1 rounded-xl leading-relaxed ${
            isDark 
              ? 'bg-[#050B16]/60 text-slate-200 ring-white/10' 
              : 'bg-slate-50 text-slate-700 ring-slate-200'
          }`}>
            {editedResponse}
          </div>
        )}
        {editedResponse && (
          <button
            onClick={() => setIsEditing(!isEditing)}
            className="mt-3 text-sm font-semibold text-[#7BAFD4] hover:text-[#9FC5E0] transition-colors flex items-center gap-1.5"
          >
            {isEditing ? (
              <>
                <span aria-hidden="true">✓</span>
                Done Editing
              </>
            ) : (
              <>
                <span aria-hidden="true">✏️</span>
                Edit Response
              </>
            )}
          </button>
        )}
      </div>

      {/* Feedback */}
      <div className="mb-6">
        <label className={`block text-xs font-semibold mb-3 uppercase tracking-wider flex items-center gap-2 ${
          isDark ? 'text-slate-500' : 'text-slate-500'
        }`}>
          <span aria-hidden="true">📝</span>
          Staff Notes (Optional)
        </label>
        <textarea
          value={feedback}
          onChange={(e) => setFeedback(e.target.value)}
          placeholder="Was the AI response helpful? Any notes for improvement?"
          className={`w-full h-20 p-4 text-sm rounded-xl ring-1 transition-all focus:ring-2 focus:ring-[#7BAFD4] focus:outline-none resize-none ${
            isDark 
              ? 'bg-[#050B16]/60 text-slate-200 ring-white/10 placeholder:text-slate-500' 
              : 'bg-slate-50 text-slate-900 ring-slate-200 placeholder:text-slate-400'
          }`}
        />
      </div>

      {/* Action Buttons */}
      <div className={`flex gap-3 pt-5 border-t ${isDark ? 'border-white/10' : 'border-slate-200'}`}>
        <button
          onClick={handleApprove}
          disabled={!editedResponse}
          className={`flex-1 py-3.5 px-5 rounded-xl font-bold text-sm shadow-lg transition-all duration-300 ${
            editedResponse
              ? 'bg-gradient-to-r from-emerald-500 to-emerald-600 text-white ring-1 ring-emerald-500/40 hover:shadow-xl hover:shadow-emerald-500/20 hover:scale-[1.02] active:scale-[0.98]'
              : isDark 
                ? 'bg-white/5 text-slate-500 cursor-not-allowed ring-1 ring-white/10'
                : 'bg-slate-100 text-slate-400 cursor-not-allowed ring-1 ring-slate-200'
          }`}
        >
          <span className="flex items-center justify-center gap-2">
            <span aria-hidden="true">✓</span>
            Approve & Send
          </span>
        </button>
        <button
          onClick={handleReject}
          className={`flex-1 py-3.5 px-5 rounded-xl font-bold text-sm shadow-lg ring-1 transition-all duration-300 hover:scale-[1.02] active:scale-[0.98] ${
            isDark 
              ? 'bg-white/10 text-white ring-white/10 hover:bg-white/15' 
              : 'bg-slate-100 text-slate-700 ring-slate-200 hover:bg-slate-200'
          }`}
        >
          <span className="flex items-center justify-center gap-2">
            <span aria-hidden="true">✗</span>
            Reject
          </span>
        </button>
      </div>
    </div>
  );
}
