import { useState, useEffect } from 'react';

export default function ApprovalPanel({ email, route, onApprove, onReject }) {
  const [isEditing, setIsEditing] = useState(false);
  const [editedResponse, setEditedResponse] = useState('');
  const [feedback, setFeedback] = useState('');

  // Update editedResponse when email changes
  useEffect(() => {
    setEditedResponse(email.generated_response || '');
    setIsEditing(false);
    setFeedback('');
  }, [email]);

  const handleApprove = () => {
    onApprove(editedResponse);
  };

  return (
    <div className="bg-white rounded-2xl shadow-lg p-8 border border-gray-200 animate-fade-in">
      {/* Route-specific UI */}
      {route === 'AI_AGENT' && (
        <div className="mb-6 p-5 bg-gradient-to-r from-green-50 to-emerald-50 border-2 border-green-300 rounded-xl shadow-sm">
          <p className="text-base font-bold text-green-900 mb-2">
            🤖 AI Agent Response Ready
          </p>
          <p className="text-sm text-green-800 leading-relaxed">
            This response was generated by the AI agent using your FAQ knowledge base. 
            Review and edit if needed, then approve to send.
          </p>
        </div>
      )}

      {route === 'HUMAN_REQUIRED' && (
        <div className="mb-6 p-5 bg-gradient-to-r from-yellow-50 to-amber-50 border-2 border-yellow-400 rounded-xl shadow-sm">
          <p className="text-base font-bold text-yellow-900 mb-2">
            👤 Manual Response Required
          </p>
          <p className="text-sm text-yellow-800 leading-relaxed">
            This email requires human judgment. Please compose a response below.
          </p>
        </div>
      )}

      {/* Suggested Response */}
      <div className="mb-6">
        <label className="block text-base font-bold text-gray-800 mb-4 uppercase tracking-wide">
          {route === 'AI_AGENT' ? '🤖 AI-Generated Response' : '✍️ Your Response'}
        </label>
        {isEditing || !editedResponse ? (
          <textarea
            value={editedResponse}
            onChange={(e) => setEditedResponse(e.target.value)}
            className="w-full min-h-[400px] p-5 border-2 border-gray-300 rounded-xl text-base focus:border-blue-500 focus:ring-2 focus:ring-blue-200 transition-all resize-y leading-relaxed"
            placeholder="Type your response here..."
          />
        ) : (
          <div className="w-full min-h-[400px] max-h-[500px] p-5 bg-gray-50 overflow-y-auto text-base whitespace-pre-wrap border-2 border-gray-200 rounded-xl leading-relaxed">
            {editedResponse}
          </div>
        )}
        {editedResponse && (
          <button
            onClick={() => setIsEditing(!isEditing)}
            className="mt-4 text-base font-semibold text-blue-600 hover:text-blue-800 hover:underline transition-colors"
          >
            {isEditing ? '✓ Done Editing' : '✏️ Edit Response'}
          </button>
        )}
      </div>

      {/* Feedback */}
      <div className="mb-6">
        <label className="block text-base font-bold text-gray-800 mb-4 uppercase tracking-wide">
          📝 Staff Notes (Optional)
        </label>
        <textarea
          value={feedback}
          onChange={(e) => setFeedback(e.target.value)}
          placeholder="Was the AI response helpful? Any notes for improvement?"
          className="w-full h-20 p-4 border-2 border-gray-300 rounded-xl text-base focus:border-blue-500 focus:ring-2 focus:ring-blue-200 transition-all resize-none"
        />
      </div>

      {/* Action Buttons */}
      <div className="flex gap-4 pt-6 border-t-2 border-gray-200">
        <button
          onClick={handleApprove}
          disabled={!editedResponse}
          className={`flex-1 py-4 px-6 rounded-xl font-bold text-lg shadow-md transition-all duration-200 ${
            editedResponse
              ? 'bg-gradient-to-r from-green-600 to-emerald-600 text-white hover:from-green-700 hover:to-emerald-700 hover:shadow-lg transform hover:scale-105'
              : 'bg-gray-300 text-gray-500 cursor-not-allowed'
          }`}
        >
          ✓ Approve & Send
        </button>
        <button
          onClick={onReject}
          className="flex-1 bg-gradient-to-r from-gray-500 to-gray-600 text-white py-4 px-6 rounded-xl hover:from-gray-600 hover:to-gray-700 font-bold text-lg shadow-md hover:shadow-lg transform hover:scale-105 transition-all duration-200"
        >
          ⚠️ Flag for Review
        </button>
      </div>
    </div>
  );
}
